//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Table.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("USB2.0 PC CAMERA")]
        public string VideoDevice {
            get {
                return ((string)(this["VideoDevice"]));
            }
            set {
                this["VideoDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("USB2.0 MIC")]
        public string AudioDevice {
            get {
                return ((string)(this["AudioDevice"]));
            }
            set {
                this["AudioDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:15")]
        public global::System.TimeSpan PressClipLength {
            get {
                return ((global::System.TimeSpan)(this["PressClipLength"]));
            }
            set {
                this["PressClipLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Research question")]
        public string ResearchQuestion {
            get {
                return ((string)(this["ResearchQuestion"]));
            }
            set {
                this["ResearchQuestion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Round one instructions Round one instructions Round one instructions Round one instructions Round one instructions Round one instructions Round one instructions Round one instructions Round one instructions Round one instructions Round one instructions Round one instructions Round one instructions Round one instructions Round one instructions Round one instructions Round one instructions Round one instructions Round one instructions Round one instructions Round one instructions Round one instructions Round one instructions Round one instructions ")]
        public string Round_1_Instructions {
            get {
                return ((string)(this["Round_1_Instructions"]));
            }
            set {
                this["Round_1_Instructions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Round two instructions")]
        public string Round_2_Instructions {
            get {
                return ((string)(this["Round_2_Instructions"]));
            }
            set {
                this["Round_2_Instructions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Round three instructions")]
        public string Round_3_Instructions {
            get {
                return ((string)(this["Round_3_Instructions"]));
            }
            set {
                this["Round_3_Instructions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Round four instructions")]
        public string Round_4_Instructions {
            get {
                return ((string)(this["Round_4_Instructions"]));
            }
            set {
                this["Round_4_Instructions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Round five instructions")]
        public string Round_5_Instructions {
            get {
                return ((string)(this["Round_5_Instructions"]));
            }
            set {
                this["Round_5_Instructions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Round six instructions")]
        public string Round_6_Instructions {
            get {
                return ((string)(this["Round_6_Instructions"]));
            }
            set {
                this["Round_6_Instructions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:10")]
        public global::System.TimeSpan Round_2_Time {
            get {
                return ((global::System.TimeSpan)(this["Round_2_Time"]));
            }
            set {
                this["Round_2_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:10")]
        public global::System.TimeSpan Round_3_Time {
            get {
                return ((global::System.TimeSpan)(this["Round_3_Time"]));
            }
            set {
                this["Round_3_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:10")]
        public global::System.TimeSpan Round_4_Time {
            get {
                return ((global::System.TimeSpan)(this["Round_4_Time"]));
            }
            set {
                this["Round_4_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:10")]
        public global::System.TimeSpan Round_5_Time {
            get {
                return ((global::System.TimeSpan)(this["Round_5_Time"]));
            }
            set {
                this["Round_5_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:10")]
        public global::System.TimeSpan Round_6_Time {
            get {
                return ((global::System.TimeSpan)(this["Round_6_Time"]));
            }
            set {
                this["Round_6_Time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Video processing instructions")]
        public string Video_Processing_Instructions {
            get {
                return ((string)(this["Video_Processing_Instructions"]));
            }
            set {
                this["Video_Processing_Instructions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Complete instructions")]
        public string Complete_Instructions {
            get {
                return ((string)(this["Complete_Instructions"]));
            }
            set {
                this["Complete_Instructions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("238, 127, 0")]
        public global::System.Drawing.Color User0Colour {
            get {
                return ((global::System.Drawing.Color)(this["User0Colour"]));
            }
            set {
                this["User0Colour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("64, 189, 185")]
        public global::System.Drawing.Color User1Colour {
            get {
                return ((global::System.Drawing.Color)(this["User1Colour"]));
            }
            set {
                this["User1Colour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("122, 181, 29")]
        public global::System.Drawing.Color User2Colour {
            get {
                return ((global::System.Drawing.Color)(this["User2Colour"]));
            }
            set {
                this["User2Colour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("226, 0, 122")]
        public global::System.Drawing.Color User3Colour {
            get {
                return ((global::System.Drawing.Color)(this["User3Colour"]));
            }
            set {
                this["User3Colour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:10")]
        public global::System.TimeSpan Round_1_Time {
            get {
                return ((global::System.TimeSpan)(this["Round_1_Time"]));
            }
            set {
                this["Round_1_Time"] = value;
            }
        }
    }
}
